### ISSUE TITLE
viewcube plugin affects spawn TextBundle 

### ISSUE THREAD

**Issue by piaoger** [Donvlouss/bevy_viewcube#1]
Just run viewcube example and you will see below behavior: the text tips are draw twice unexpected and one is vague. I added another simple TextBundle and found similar behavior.

![image](https://github.com/Donvlouss/bevy_viewcube/assets/179429/669bb82f-bc9a-490f-bd2c-7da22f35b718)

**Comment by Donvlouss** [comment]
I know this ISSUE, which should be caused by the original Raycast and MOD_PICKING. Simple testing, as long as the Camera of different Physical_size of ViewPort exists, he will happen.

I am testing the MOD_PICKING version of the BEVY 0.13 version, which seems to have fixed this problem.
But the current version seems to have some problems in the UI between different ViewPort.

I also update the BEVY version of this Repository to 0.13. Because this is a UI problem, you can use the following disabled MOD_Pick UI display:
`.insert_resource(DebugPickingMode::default())`

**Comment by piaoger** [comment]
I tried to add simple TextBundle and also found this issue. Not sure if it is caused by picking plungin or something else.
